# OPEN CV

In [1]:
#installation


In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install --upgrade opencv-python

Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2
import numpy as np

# Load/Read image

In [4]:
# load an image using 'imread' specifying the path to image

img = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg",1)

# Lets take a closer look at how images are stored

In [5]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# shape gives the dimensions of the image array

In [6]:
img.shape

(1358, 1500, 3)

# Display the image

In [7]:
# to display our image variable . we use 'imshow'
#the first parameter will be title show on the image
# the second parameter is the image variable

cv2.imshow("PM", img)

# 'waitkey' allows us to input information when a image window is opem
# by leaving it blank it just waits for anykey to be pressed before countinuing
# by placing numbers (except 0 ), we can specify a delay for
# how long you keep the window open (time is in milliseconds here)

cv2.waitKey(2000)

#this closes all open windows
#failure to place this will cause your program to hang

cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")
cv2.imshow("PM", img)
cv2.waitKey()
cv2.destroyAllWindows()

# Save image

In [8]:
# simply use 'imwrite' specificing the file name and the image to be saved

cv2.imwrite("pm_pic.jpg",img)

True

# Resize image

In [9]:
img = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")

resized_image = cv2.resize(img,(500,500))
    
gray =  cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Modi img',gray)

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img.shape[0]*0.5

679.0

In [11]:
img.shape[1]*0.5

750.0

# Face Detection using HAAR cascade classifier

In [12]:
# we point opencv's cascadeclassifier funcion to where our classifier(XML file format) is stored

face_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_frontalface_default.xml")

In [13]:
#load our  image the convert it to grayscale
image = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

### tuning cascade classifier - detectMultiscale(input image, **scale factor** , ** min neighbours)

faces = face_classifier.detectMultiScale(gray, 1.05, 5)

# scale factor - specifies how much we reduce the image size each time we scale.

# e.g. in face detection we typically use 1.3. this means we reduce the image by 30% each time it's 

# smaller values , like 1.05 will take longer to compute, but will increase the rate of detection.

## min Neighbours**

#specifies the number of neighbours each potential window should have in order to consider it a positive detection.

# typically set between 3-6

# it acts as sensitivity  setting,low values will sometimes detech multiples faces over a single face.

#high values will ensure less false positives,but you may miss some faces

In [14]:
print (faces)

[[205  79 217 217]]


In [15]:
## we point opencv's cascadeclassifier funcion to where our classifier(XML file format) is stored

face_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_frontalface_default.xml")

# load our image then convert it to grayscale
image = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#### tuning cascade classifier - detectMultiscale(input image, **scale factor** , ** min neighbours)

faces = face_classifier.detectMultiScale(gray, 1.05, 5)


#load our  image the convert it to grayscale
image = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

### tuning cascade classifier - detectMultiscale(input image, **scale factor** , ** min neighbours)

faces = face_classifier.detectMultiScale(gray, 1.05, 5)

# scale factor - specifies how much we reduce the image size each time we scale.

# e.g. in face detection we typically use 1.3. this means we reduce the image by 30% each time it's 

# smaller values , like 1.05 will take longer to compute, but will increase the rate of detection.

## min Neighbours**

#specifies the number of neighbours each potential window should have in order to consider it a positive detection.

# typically set between 3-6

# it acts as sensitivity  setting,low values will sometimes detech multiples faces over a single face.

#high values will ensure less false positives,but you may miss some faces

# when no faces detected, face_classifier retruns and empty tuple
if faces is ():
    print("NO faces found")

# we iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,100), 1)
    
    
cv2.imshow("Face Detection", image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:41: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:41: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\saisu\AppData\Local\Temp\ipykernel_11472\574044032.py:41: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Face & Eye detection using HAAR cascade classifiers in image

In [16]:
face_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_eye.xml")

img = cv2.imread("C:\\Users\\saisu\\Downloads\\Modi.jpg")
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# when no faces detected, face_classifier retruns and empty tuple
if faces is ():
    print("NO faces found")

# we iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (255,0,0), 2)
    roi_gray = gray[y:y+h, x:x+y]
    roi_color = resized_image[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
cv2.imshow("img", resized_image)
cv2.waitKey(0)

cv2.destroyAllWindows()


<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\saisu\AppData\Local\Temp\ipykernel_11472\1221590260.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# capture a video

In [ ]:
# doing some face recognition with the web

import cv2
video = cv2.VideoCapture(0)  #)=0 --webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1) == ord('q'):
        break
    
video.release()
cv2.destroyAllWindows()

# Face & eye detection using HAAR cascade classifiers

In [ ]:
# defining a function that will do the detections

face_cascade = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_eye.xml")


def detect(gray, frame): 
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        roi_gray = gray[y:y+h, x:x+y]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 3)
    
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 255, 0),2)
        
    return frame

# doing some face recognition with the web

video = cv2.VideoCapture(0)  #)=0 --webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)
    cv2.imshow('Video', canvas)
    if cv2.waitKey(1) == ord('q'):
        break
    
video.release()
cv2.destroyAllWindows()


# Pedistrian Detection 

In [ ]:
import cv2

# create our body classifier
body_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_fullbody.xml")

#initiate video capture for video file
cap = cv2.VideoCapture("C:\\Users\\saisu\\Downloads\\Walking.avi")

#loop once video is successfully loaded

while cap.isOpened():
    
    #read first frame
    check, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #pass frame to our body classifer
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3)
    
    #extract bounding boxes for any bodies identified
    for(x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 255), 2)
        cv2.imshow("Pedestraians", frame)
        
    if cv2.waitKey(1)== ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
    
    

In [ ]:
import time

#create our body classifier

car_classifier = cv2.CascadeClassifier("C:\\Users\\saisu\\OneDrive\\Documents\\haarcascade_car.xml")

#initiate video capture for video file

cap = cv2.VideoCapture("C:\\Users\\saisu\\cars.avi")

#loop once video is successfully loaded
while cap.isOpened():
    
    time.sleep(.05)
    #read frist frame
    
    check, frame = cap.read()
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # pass frame to our car classifier
    cars = car_classifier.detechMultiScale(gray, 1.4, 2)
    
    #extract bounding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Cars', frame)
        
    if cv2.waitKey(1) == ord('q'):
        break 
    
cap.release()
cv2.destroyAllWindows()